# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'islamikplus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for screenbreak
pod 'GooglePlaces'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'IQDropDownTextField'
pod 'AAPullToRefresh'
pod 'AFNetworking', '~> 4.0'
pod 'NSString-Email'
pod 'NSString-UrlEncode'
pod 'Reachability'
pod 'NSDate-Time-Ago'
pod 'MGSwipeTableCell'
pod 'SDWebImage'
pod 'Parse'
pod 'HCSStarRatingView'
pod 'DMActivityInstagram'
pod "IQAudioRecorderController"
pod 'JSQMessagesViewController'
end
